# 10300. Explore entities relations
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX void-ext: <http://ldf.fi/void-ext#>
SELECT DISTINCT ?graph ?classCount1 ?class1 ?relationWith ?classCount2 ?class2
WHERE {
  GRAPH ?g {
    ?graph a void:Dataset .
    ?graph void:propertyPartition [
        void:property ?relationWith ;
        void:classPartition [
            void:class ?class1 ;
            void:distinctSubjects ?classCount1 ;
        ];
        void-ext:objectClassPartition [
          void:class ?class2 ;
          void:distinctObjects ?classCount2 ;
    ]] .
  }
} ORDER BY DESC(?classCount1)